apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: amitp-poi-map-app-dev
  annotations:
    argocd/app-name: amitp-poi-map-app-dev
    backstage.io/kubernetes-id: amitp-poi-map-app
    backstage.io/kubernetes-namespace: amitp
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/amitp-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/amitp/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/amitp/deployments/amitp-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/amitp-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://amitp-poi-map-app-amitp.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/amitp"
  system: workshop-system-amitp
  consumesApis:
    - gateway-api-amitp
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-amitp
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/amitp"
